services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    volumes:
      - ./ollama/.ollama:/root/.ollama
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    environment:
      OLLAMA_API_BASE_URL: http://ollama:11434
    depends_on:
      - ollama
    restart: always
    volumes:
      - ./open-webui/data:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - webui_network
networks:
  webui_network:
    driver: bridge
